language: node_js
node_js:
    - "4.2"
before_install:
    - rvm install 2.1.5
    - ./bootstrap/setup
    - ./bootstrap/config -p asoc -h LAN -nomail
    - ./bootstrap/testDataset/testDataset no-wait
    - ./bootstrap/edt/edt no-wait
notifications:
      email: false
