language: node_js
node_js:
    - "0.10"
before_install:
    - curl -sSL https://get.rvm.io | bash -s stable --ruby
    - cd bootstrap && ./setup
    - ./config asoc LOC
    - cd ../server/bin && ./neoRun 
    - cd ../../bootstrap/testDataset && ./testDataset no-wait
    - cd ../../server/bin && ./neoStop
notifications:
      email: false
