language: node_js
node_js:
    - "stable"
before_install:
    - curl -sSL https://get.rvm.io | bash -s stable --ruby
    - ./bootstrap/setup
    - ./bootstrap/config asoc LAN
    - ./bootstrap/testDataset/testDataset no-wait
notifications:
      email: false
