language: node_js
node_js:
    - "stable"
before_install:
    - curl -sSL https://get.rvm.io | bash -s stable --ruby
    - ./bootstrap/setup
    - ./bootstrap/config asoc LAN
    - ./bootstrap/testDataset/testDataset no-wait
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
notifications:
      email: false
