language: node_js
node_js:
    - "stable"
before_install:
    - rvm install 2.1.5
    - ./bootstrap/setup
    - ./bootstrap/config asoc LAN
    - ./bootstrap/testDataset/testDataset no-wait
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
notifications:
      email: false
