language: node_js
node_js:
    - "stable"
before_install:
    - rvm install 2.1.5
    - ./bootstrap/setup
    - ./bootstrap/config asoc LAN
    - ./bootstrap/testDataset/testDataset no-wait
    - ./bootstrap/edt/edt no-wait
notifications:
      email: false
