language: node_js
node_js:
    - "0.10"
before_install:
    - curl -sSL https://get.rvm.io | bash -s stable --ruby
    - ./setup.sh
    - ./config.sh asoc LOC
    - cd testDataset && ./testDataset.sh no-wait
notifications:
      email: false
