#!/bin/bash

# Get program arguments
VERBOSE=false
while getopts ":v" opt; do
  case $opt in
    v)
      echo "Verbose mode active" >&2
      VERBOSE=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

DEPS="npm
gem
git"

MY_PATH="`dirname \"$0\"`"
MY_PATH="`( cd \"$MY_PATH\" && pwd )`"  # absolutized and normalized

NEO4J_VER=2.3.3

TMP_DOWNLOAD_DIR=$MY_PATH/tmp_download_dir
NEO4J_FILE=$TMP_DOWNLOAD_DIR/neo4j-community-$NEO4J_VER-unix.tar.gz

if [ "$VERBOSE" = false ]; then
  LOG_FILE=$MY_PATH/bootstrap.log
fi

BIN_DIR=../server/bin
LOCATION_FILE=$MY_PATH/rightLocation
NEO4J_DIR=$BIN_DIR/neo4j-community-$NEO4J_VER

CONS_DIV="#####################################"
R_COL="\e[31m"
G_COL="\e[92m"
DEF_COL="\e[39m"

function loggerGreen {
	echo -e $G_COL$1$DEF_COL
  if [ "$VERBOSE" = false ]; then
    echo -e $1 >> $LOG_FILE
  fi
}

function loggerRed {
	echo -e >&2 $R_COL$1$DEF_COL
  if [ "$VERBOSE" = false ]; then
    echo -e $1 >> $LOG_FILE
  fi
}

#----------------------------------------#

# Getting in the right location

if [ -z "$MY_PATH" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  loggerRed "Please verify permissions on bootstrap folder!\n"
  exit 1  # fail
fi
cd "$MY_PATH"

#----------------------------------------#

# Clean log file
if [ "$VERBOSE" = false ]; then
  echo "" > $LOG_FILE
fi

echo -e $G_COL$CONS_DIV"\n\n **Setup script for Red-Social-Asociacion**\n
Please install all the dependencies before running this script!!!\n
Find instructions in https://github.com/MecatronicaUncu/Red-Social-Asociacion\n\n"$CONS_DIV$DEF_COL

#----------------------------------------#
# Check dependencies

loggerGreen "Checking dependencies...\n"
for deps in $DEPS
do
  command -v $deps >/dev/null 2>&1 || { loggerRed "$deps not installed!"; exit 1; }
done
loggerGreen "Dependencies OK!\n"

#-----------------------------------------#
# Stop Neo4J Server

if [ -d "./$NEO4J_DIR/bin" ]
then
	STATUS=`./$NEO4J_DIR/bin/neo4j status`
	if [[ $STATUS != *"not"* ]]
	then
		loggerGreen "Stopping Neo4J Server...\n"
		./$BIN_DIR/neoStop >/dev/null 2>&1 || { loggerRed "Error stopping Neo4J Server!\n"; exit 1; }
	fi
fi

#----------------------------------------#
# Cleanup bin directory
loggerGreen "Cleaning bin directory...\n"
rm -rf $BIN_DIR >/dev/null 2>&1
mkdir -p $BIN_DIR

#----------------------------------------#
# Create download dir
loggerGreen "Creating tmp dir...\n"
mkdir -p $TMP_DOWNLOAD_DIR

#----------------------------------------#
# Check if bower is installed. Install if needed.
if command -v bower >/dev/null 2>&1; then
   loggerGreen "bower installed, skipping...\n";
else
  loggerGreen "Installing bower with npm (globally)...\n";
  if [ "$VERBOSE" = false ]; then
    npm install -g bower >> $LOG_FILE 2>&1 || { loggerRed "npm bower failed!. See setup.log for details"; exit 1; }
  else
    npm install -g bower  || { loggerRed "npm bower failed!. See setup.log for details"; exit 1; }
  fi
fi

#----------------------------------------#
# Download Neo4J
loggerGreen "Installing Neo4J Engine...\n"
cd $TMP_DOWNLOAD_DIR
if [ ! -e $NEO4J_FILE ] || [ ! -f $NEO4J_FILE ]
then
  if [ "$VERBOSE" = false ]; then
    curl -s -o neo4j-community-$NEO4J_VER-unix.tar.gz http://dist.neo4j.org/neo4j-community-$NEO4J_VER-unix.tar.gz | tee -a $LOG_FILE
  else
    curl -s -o neo4j-community-$NEO4J_VER-unix.tar.gz http://dist.neo4j.org/neo4j-community-$NEO4J_VER-unix.tar.gz
  fi
fi

# untar and move
if [ "$VERBOSE" = false ]; then
  tar -xvf neo4j-community-$NEO4J_VER-unix.tar.gz >> $LOG_FILE 2>&1
else
  tar -xvf neo4j-community-$NEO4J_VER-unix.tar.gz
fi
cd $MY_PATH

mv $TMP_DOWNLOAD_DIR/neo4j-community-$NEO4J_VER $BIN_DIR

# copy config files
#cp -R default/neo4j-community-2.1.5/* $NEO4J_DIR

#----------------------------------------#
# Install Sass and Compass
loggerGreen "Installing Sass and Compass...\n"
for rprog in "sass" "compass"
do
  isGemAvailable=$(gem list $rprog -i)
  if [ "$isGemAvailable" = true ]; then
    loggerGreen "$rprog gem is installed, skipping...\n"
    continue
  else
    if [ "$VERBOSE" = false ]; then
      gem install $rprog >> $LOG_FILE 2>&1 || { loggerRed 'gem $rprog failed'; exit 1; }
    else
      gem install $rprog || { loggerRed 'gem $rprog failed'; exit 1; }
    fi
  fi
done

#----------------------------------------#
# Get npm and bower dependencies
cd ..
loggerGreen "Installing Npm and Bower dependencies...\n"
if [ "$VERBOSE" = false ]; then
  npm install . >> $LOG_FILE 2>&1
  bower install -F >> $LOG_FILE 2>&1
else
  npm install .
  bower install
fi

# Install grunt-cli
if command -v grunt >/dev/null 2>&1; then
  loggerGreen "Grunt-cli installed, skipping...\n"
else
  loggerGreen "Installing grunt-cli...\n"
  if [ "$VERBOSE" = false ]; then
    npm install -g grunt-cli >> $LOG_FILE 2>&1
  else
    npm install -g grunt-cli
  fi
fi

cd $MY_PATH

#----------------------------------------#
# Create service start and shutdown scripts
loggerGreen "Installing service start and shutdown scripts...\n"

cat $LOCATION_FILE > $BIN_DIR/neoRun
echo "./neo4j-community-$NEO4J_VER/bin/neo4j start -server -Xmx512M -XX:+UseG1GC" >> $BIN_DIR/neoRun
chmod +x $BIN_DIR/neoRun

cat $LOCATION_FILE > $BIN_DIR/neoStop
echo "./neo4j-community-$NEO4J_VER/bin/neo4j stop" >> $BIN_DIR/neoStop
chmod +x $BIN_DIR/neoStop

#-----------------------------------------#
# Done!
loggerGreen "Install Ok!\n"
